name: Python package (with uv sync)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies (using uv sync)
      run: uv sync

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: check .

    - name: Test with pytest
      run: uv run pytest
